# Generated by Django 4.1.6 on 2023-02-07 19:53

from django.db import migrations


def default_values(apps, _):
    Language = apps.get_model("main", "Language")
    Language.objects.bulk_create(
        [
            Language(iso_639_1="SV", name="Swedish"),
            Language(iso_639_1="EN", name="English"),
        ]
    )

    CompanyType = apps.get_model("main", "CompanyType")
    CompanyType.objects.bulk_create(
        [
            CompanyType(type_name="producer", description="Produces things to sell"),
            CompanyType(type_name="buyer", description="Buys things"),
        ]
    )

    CompanyStatus = apps.get_model("main", "CompanyStatus")
    CompanyStatus.objects.bulk_create(
        [
            CompanyStatus(status_name="created", description="Company is created but not yet activated"),
            CompanyStatus(status_name="active", description="Company is active"),
            CompanyStatus(status_name="deactivated", description="Company has been deactivated"),
        ]
    )

    ChangeType = apps.get_model("main", "ChangeType")
    ChangeType.objects.bulk_create(
        [
            ChangeType(change_type="add"),
            ChangeType(change_type="update"),
            ChangeType(change_type="delete"),
        ]
    )

    CompanyRole = apps.get_model("main", "CompanyRole")
    CompanyRole.objects.create(role_name="company_admin")

    ContactType = apps.get_model("main", "ContactType")
    ContactType.objects.bulk_create(
        [
            ContactType(contact_type="email"),
            ContactType(contact_type="phone"),
        ]
    )

    Currency = apps.get_model("main", "Currency")
    Currency.objects.create(currency_code="SEK")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [migrations.RunPython(default_values)]
