# Generated by Django 4.1.6 on 2023-02-07 19:53

from django.db import migrations


def default_values(apps, _):
    language = apps.get_model("main", "Language")
    language.objects.create(iso_639_1="SV", name="Swedish")
    language.objects.create(iso_639_1="EN", name="English")

    company_type = apps.get_model("main", "CompanyType")
    company_type.objects.create(type_name="producer", description="Produces things to sell")
    company_type.objects.create(type_name="buyer", description="Buys things")

    company_status = apps.get_model("main", "CompanyStatus")
    company_status.objects.create(status_name="created", description="Company is created but not yet activated")
    company_status.objects.create(status_name="active", description="Company is active")
    company_status.objects.create(status_name="deactivated", description="Company has been deactivated")

    change_type = apps.get_model("main", "ChangeType")
    change_type.objects.create(change_type="add")
    change_type.objects.create(change_type="update")
    change_type.objects.create(change_type="delete")

    company_role = apps.get_model("main", "CompanyRole")
    company_role.objects.create(role_name="company_admin")

    contact_type = apps.get_model("main", "ContactType")
    contact_type.objects.create(contact_type="email")
    contact_type.objects.create(contact_type="phone")

    currency = apps.get_model("main", "Currency")
    currency.objects.create(currency_code="SEK")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [migrations.RunPython(default_values)]
