# Generated by Django 4.1.6 on 2023-02-07 19:53

from django.db import migrations


def default_values(apps, _):
    Language = apps.get_model("main", "Language")
    Language.objects.create(iso_639_1="SV", name="Swedish")
    Language.objects.create(iso_639_1="EN", name="English")

    CompanyType = apps.get_model("main", "CompanyType")
    CompanyType.objects.create(type_name="producer", description="Produces things to sell")
    CompanyType.objects.create(type_name="buyer", description="Buys things")

    CompanyStatus = apps.get_model("main", "CompanyStatus")
    CompanyStatus.objects.create(status_name="created", description="Company is created but not yet activated")
    CompanyStatus.objects.create(status_name="active", description="Company is active")
    CompanyStatus.objects.create(status_name="deactivated", description="Company has been deactivated")

    ChangeType = apps.get_model("main", "ChangeType")
    ChangeType.objects.create(change_type="add")
    ChangeType.objects.create(change_type="update")
    ChangeType.objects.create(change_type="delete")

    CompanyRole = apps.get_model("main", "CompanyRole")
    CompanyRole.objects.create(role_name="company_admin")

    ContactType = apps.get_model("main", "ContactType")
    ContactType.objects.create(contact_type="email")
    ContactType.objects.create(contact_type="phone")

    Currency = apps.get_model("main", "Currency")
    Currency.objects.create(currency_code="SEK")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [migrations.RunPython(default_values)]
