# Generated by Django 4.1.6 on 2023-02-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_default_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="currency",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
