# Generated by Django 4.1.6 on 2023-02-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_order_currency_delete_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(choices=[("SEK", "SEK")], default="SEK", max_length=3),
            preserve_default=False,
        ),
    ]
