# Generated by Django 4.1.3 on 2022-12-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_name_delete_companynames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main.company'),
        ),
    ]
