# Generated by Django 4.1.6 on 2023-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_order_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productname",
            name="language",
        ),
        migrations.RemoveField(
            model_name="productname",
            name="product",
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductName",
        ),
    ]
