# Generated by Django 4.1.6 on 2023-02-10 21:50

from django.db import migrations


def add_order_admin(apps, _):
    company_role_model = apps.get_model("main", "CompanyRole")
    company_role_model.objects.create(
        role_name="order_admin",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_companytype_type_name_en_and_more"),
    ]

    operations = [migrations.RunPython(add_order_admin)]
