# Generated by Django 4.1.6 on 2023-02-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_add_order_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main.company",
            ),
        ),
    ]
