# Generated by Django 4.1.3 on 2022-12-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_companytype_type_name_en_companytype_type_name_sv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="profile_picture_url",
        ),
        migrations.AddField(
            model_name="company",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:\\git\\private\\produce-exchange-hub\\farmers-market\\farmers_market\\company_profile_pictures",
            ),
        ),
    ]
