# Generated by Django 4.1.3 on 2022-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_company_profile_picture_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_profile_picture"
            ),
        ),
    ]
