# Generated by Django 4.1.3 on 2022-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_company_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="company_profile_picture/"),
        ),
    ]
