# Generated by Django 4.1.3 on 2022-12-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_company_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "companies"},
        ),
    ]
