# Generated by Django 4.1.3 on 2022-12-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_company_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "company", "verbose_name_plural": "companies"},
        ),
        migrations.AlterField(
            model_name="company",
            name="external_website_url",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="company_profile_picture"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.ForeignKey(
                default="created",
                on_delete=django.db.models.deletion.PROTECT,
                to="main.companystatus",
                to_field="status_name",
            ),
        ),
        migrations.AlterField(
            model_name="companyrole",
            name="role_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="companystatus",
            name="status_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="companytype",
            name="type_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="companytype",
            name="type_name_en",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="companytype",
            name="type_name_sv",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="contacttype",
            name="contact_type",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="country_iso_3166_1",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="currency_code",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="iso_639_1",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
