# Generated by Django 4.1.3 on 2022-12-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.companystatus"
            ),
        ),
    ]
