# Generated by Django 4.1.3 on 2022-12-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_address_options_alter_companystatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companystatus",
            options={
                "verbose_name": "Company Status",
                "verbose_name_plural": "Company Statuses",
            },
        ),
    ]
