# Generated by Django 4.1.3 on 2022-12-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_companystatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
    ]
