# Generated by Django 4.1.3 on 2022-12-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_currency_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
