# Generated by Django 4.1.3 on 2022-12-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
