# Generated by Django 4.1.3 on 2023-01-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
        ("main", "0023_alter_company_company_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shared.country",
            ),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
