# Generated by Django 4.1.3 on 2023-01-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_companyuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("sell", "Sell order"), ("buy", "Buy order")],
                default="sell",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
