# Generated by Django 4.1.3 on 2023-01-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_order_order_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price_per_unit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="unit_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="productname",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="name_translations",
                to="main.product",
            ),
        ),
    ]
