from .activate_company_tests import *
from .add_contact_tests import *
from .company_model_tests import *
from .company_profile_picture_tests import *
from .company_users_tests import *
from .deactivate_company_tests import *
from .decorators_tests import *
from .delete_address_tests import *
from .delete_contact_tests import *
from .edit_company_view_tests import *
from .new_company_tests import *
from .orders import *
from .index_tests import *
from .company_view_tests import *
