# Generated by Django 4.1.3 on 2023-01-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shared.country",
            ),
        ),
    ]
