# Generated by Django 4.1.3 on 2023-01-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_iso_3166_1", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
    ]
