# Generated by Django 4.1.6 on 2023-02-07 19:46

from django.db import migrations


def default_values(apps, _):
    Country = apps.get_model("shared", "Country")
    Country.objects.create(country_iso_3166_1="SE", name="Sweden")


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [migrations.RunPython(default_values)]
