name: Python Django CI (Flake8, Test)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ./farmers-market/farmers_market
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Analysing the code with flake8
      working-directory: ./farmers-market/farmers_market
      run: |
        flake8
    - name: Run tests
      working-directory: ./farmers-market/farmers_market
      run: |
        python manage.py test
